* About
A set of ~pixi~ environments to handle the sub-environments within the ~atomistic-cookbook~
** Usage
Clone the repository into this directory:
#+begin_src bash
# Most likely you'd want a fork though
git clone git@github.com:lab-cosmo/atomistic-cookbook.git
#+end_src
Now each example has a corresponding ~pixi~ environment to assist interactive work.
#+begin_src bash
pixi s -e lpr
cd atomistic-cookbook/examples/
python lpr.py
#+end_src
** Interactivity
Beyond the "production" environments for each example, we include environments
to assist working on new recipes.
*** Jupyter server
For an interactive writing experience, the ~jup~ environment may be used. This
can be used for interactive editing with the ~to-ipynb~ task:
#+begin_src bash
pixi r -e lpr to-ipynb
#+end_src
Which will generate easy to work on variants of the ~.py~ files. If you would like to get them all...
#+begin_src bash
pixi r -e jup serve
#+end_src
This builds each ~ipynb~ and registers the kernel for them within the Jupyter server. To get the ~py~ back:
#+begin_src bash
pixi r -e jup py-sphinx lpr
#+end_src
There are additional ~nox~ based commands which echo the usage within the ~contributing~ guidelines of atomistic cookbook.
