[workspace]
authors = ["Rohit Goswami <rgoswami@ieee.org>"]
channels = ["conda-forge"]
name = "vesin"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
cmake = ">=3.30,<4"
ninja = ">=1.12,<2"
cxx-compiler = ">=1.9,<2"
pytest = ">=9.0,<10"
uv = ">=0.7,<1"
pip = ">=25.2,<26"
matplotlib = ">=3.9,<4"
numpy = ">=2.0,<3"

[tasks]
configure = { cwd = "vesin", cmd = "cmake -B build -G Ninja -DVESIN_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release" }
build = { cwd = "vesin", cmd = "cmake --build build", depends-on = ["configure"] }
build-shared = { cwd = "vesin", cmd = "cmake -B build-shared -G Ninja -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release && cmake --build build-shared && mkdir -p python/vesin/vesin/lib && cp build-shared/vesin/libvesin.so python/vesin/vesin/lib/" }
test-c = { cwd = "vesin", cmd = "build/vesin/tests/neighbors && build/vesin/tests/memory && build/vesin/tests/verlet", depends-on = ["build"] }
install-python = { cwd = "vesin/python/vesin", cmd = "pip install --no-build-isolation -e .", depends-on = ["build-shared"] }
test-python = { cwd = "vesin", cmd = "pytest python/vesin/tests/ -v", depends-on = ["install-python"] }
test-verlet = { cwd = "vesin", cmd = "pytest python/vesin/tests/test_verlet.py -v", depends-on = ["install-python"] }
bench-prepare = { cwd = "vesin_bench", cmd = "python prepare.py" }
bench-run = { cwd = "vesin_bench", cmd = "python bench_nl.py", depends-on = ["install-python", "bench-prepare"] }
bench-plot = { cwd = "vesin_bench", cmd = "python plot.py" }

[feature.cuda.dependencies]
cuda-toolkit = ">=13.1.0,<14"
cuda-compiler = ">=13.0.1,<14"
cuda-libraries-dev = ">=13.0.1,<14"
cuda-version = ">=13.0,<14"
cuda-nvcc = ">=13.1.80,<14"
cuda-cudart-dev = ">=13.1.80,<14"
cuda-driver-dev = ">=13.1.80,<14"
pytorch = { version = ">=2.9.1,<3", build = "cuda*" }

[feature.cuda.system-requirements]
cuda = "13.0"

[feature.cuda.tasks]
test-cuda = { cwd = "vesin", cmd = "ctest --test-dir build -R cuda -V", depends-on = ["build"] }

[feature.nocuda.activation]
env = { CUDA_VISIBLE_DEVICES = "" }

[feature.nocuda.dependencies]
pytorch = ">=2.9.1,<3"

[feature.nocuda.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cpu"]

[feature.nocuda.pypi-dependencies]
metatomic-torch = ">=0.1.3,<0.2"
metatensor-torch = ">=0.7,<1"

[feature.pybase.dependencies]
python = ">=3.12,<3.13"
pycparser = ">=2.22,<3"

[environments]
default = {features = ["pybase", "nocuda"]}
cuda = {features = ["pybase", "cuda"]}
