* About
Helper for integrating ~metatomic~ into GROMACS.

The primary development repository functions as a GitLab fork. Contributors should clone and work with this fork for all major development:
#+begin_src bash
git clone https://gitlab.com/HaoZeke/gromacs.git
#+end_src
- This fork connects with the upstream GitLab GROMACS for an eventual "MR," or merge request.
- The project also maintains a GitHub mirror on the =metatensor= organization.
  + Developers may submit pull requests, or "PRs" to this mirror.

Regardless of where a contribution begins, a single merge request for
=metatomic= proceeds through the GitLab fork to the GROMACS upstream repository.
** Usage
Standard builds:
#+begin_src bash
# or Debug
pixi r gromk Release
cd mta_test
python create_model.py
# pairlist has no gmx_mpi support
# anyway threadmpi works beter in GROMACS land
gmx grompp
gmx mdrun
# or, better
pytest
#+end_src
Profit.
** Development details
For working remotely, consider the ~to~ and ~from~ tasks.
Meant for usage with remote servers.
#+begin_src bash
# make changes
pixi r syncer to luthaf.cosmolab
# ssh onto remote host and build
#+end_src
*** Scratch [outdated]
Basic build:
#+begin_src bash
cd gromacs
mkdir build
cd build
cmake .. \
    -DGMX_BUILD_OWN_FFTW=ON \
    -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
    -DCMAKE_C_COMPILER_LAUNCHER=sccache \
    -DCMAKE_CXX_COMPILER=$(which clang++) \
    -DCMAKE_C_COMPILER=$(which clang) \
    -DGMX_MPI=yes \
    -DCMAKE_BUILD_TYPE=Debug
make -j$(nproc)
cmake install --install-prefix $CONDA_PREFIX
#+end_src
Easier with the ~pixi~ environment:
#+begin_src bash
pixi s -e metatomic
# Optional but recommended for logging
# cargo binstall bless
cd gromacs
mkdir build; cd $_
export TORCH_PREFIX=$(python -c "import torch; print(torch.utils.cmake_prefix_path)")
export MTS_PREFIX=$(python -c "import metatensor; print(metatensor.utils.cmake_prefix_path)")
export MTS_TORCH_PREFIX=$(python -c "import metatensor.torch; print(metatensor.torch.utils.cmake_prefix_path)")
export MTA_TORCH_PREFIX=$(python -c "import metatomic.torch; print(metatomic.torch.utils.cmake_prefix_path)")
export CMAKE_PREFIX_PATH="$TORCH_PREFIX;$MTS_PREFIX;$MTS_TORCH_PREFIX;$MTA_TORCH_PREFIX"
# drop bless -- if not installed
bless -- cmake .. \
    -DGMX_BUILD_OWN_FFTW=OFF \
    -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
    -DCMAKE_C_COMPILER_LAUNCHER=sccache \
    -DGMX_MPI=yes \
    -DGMX_METATOMIC=yes \
    -DBUILD_TESTING=OFF \
    -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH" \
    -DCMAKE_BUILD_TYPE=Debug \
    -DDOWNLOAD_VESIN=yes \
    -DGPU_DEVICE=CUDA \
    -DCUDA_TOOLKIT_ROOT_DIR=$CONDA_PREFIX/targets/x86_64-linux \
    -Dnvtx3_dir=$CONDA_PREFIX/targets/x86_64-linux/include/nvtx3 \
    -DCMAKE_CXX_FLAGS="-D_LIBCPP_DISABLE_AVAILABILITY -I$CONDA_PREFIX/targets/x86_64-linux/include/ -I../src"

cmake --build . --parallel $(nproc)
cmake install . --install-prefix $CONDA_PREFIX
cmake --build . --target install
#+end_src

#+begin_src bash
# local compilers
bless -- cmake ..     -DGMX_BUILD_OWN_FFTW=OFF     -DCMAKE_CXX_COMPILER_LAUNCHER=sccache     -DCMAKE_C_COMPILER_LAUNCHER=sccache     -DGMX_MPI=OFF -DGMX_METATOMIC=yes      -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH"     -DCMAKE_BUILD_TYPE=Debug     -DDOWNLOAD_VESIN=yes     -DGPU_DEVICE=CUDA  -DBUILD_TESTING=ON
make check # builds and runs tests
gmx_mpi grompp -maxwarn 10
gmx_mpi mdrun
#+end_src

mkdir -p build && \
cd build && \
export TORCH_PREFIX=$(python -c "import torch; print(torch.utils.cmake_prefix_path)") && \
export MTS_PREFIX=$(python -c "import metatensor; print(metatensor.utils.cmake_prefix_path)") && \
export MTS_TORCH_PREFIX=$(python -c "import metatensor.torch; print(metatensor.torch.utils.cmake_prefix_path)") && \
export MTA_TORCH_PREFIX=$(python -c "import metatomic.torch; print(metatomic.torch.utils.cmake_prefix_path)") && \
export CMAKE_PREFIX_PATH="$TORCH_PREFIX;$MTS_PREFIX;$MTS_TORCH_PREFIX;$MTA_TORCH_PREFIX;$CMAKE_PREFIX_PATH" && \
cmake .. \
 -DGMX_BUILD_OWN_FFTW=ON \
 -DGMX_GPU=CUDA \
 -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH" \
 -DTorch_DIR=$TORCH_PREFIX/Torch \
 -DGMX_METATOMIC=ON \
 -DDOWNLOAD_VESIN=ON \
 -DCUDAToolkit_ROOT=$CONDA_PREFIX
